package com.briup.apps.poll.bean;

public class SchoolWithBLOBs extends School {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poll_school.description
     *
     * @mbg.generated Mon Jun 25 16:38:06 CST 2018
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poll_school.address
     *
     * @mbg.generated Mon Jun 25 16:38:06 CST 2018
     */
    private String address;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poll_school.description
     *
     * @return the value of poll_school.description
     *
     * @mbg.generated Mon Jun 25 16:38:06 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poll_school.description
     *
     * @param description the value for poll_school.description
     *
     * @mbg.generated Mon Jun 25 16:38:06 CST 2018
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poll_school.address
     *
     * @return the value of poll_school.address
     *
     * @mbg.generated Mon Jun 25 16:38:06 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poll_school.address
     *
     * @param address the value for poll_school.address
     *
     * @mbg.generated Mon Jun 25 16:38:06 CST 2018
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }
}