package com.briup.apps.poll.dao;

import com.briup.apps.poll.bean.School;
import com.briup.apps.poll.bean.SchoolExample;
import com.briup.apps.poll.bean.SchoolWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SchoolMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poll_school
     *
     * @mbg.generated Mon Jun 25 16:38:06 CST 2018
     */
    long countByExample(SchoolExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poll_school
     *
     * @mbg.generated Mon Jun 25 16:38:06 CST 2018
     */
    int deleteByExample(SchoolExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poll_school
     *
     * @mbg.generated Mon Jun 25 16:38:06 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poll_school
     *
     * @mbg.generated Mon Jun 25 16:38:06 CST 2018
     */
    int insert(SchoolWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poll_school
     *
     * @mbg.generated Mon Jun 25 16:38:06 CST 2018
     */
    int insertSelective(SchoolWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poll_school
     *
     * @mbg.generated Mon Jun 25 16:38:06 CST 2018
     */
    List<SchoolWithBLOBs> selectByExampleWithBLOBs(SchoolExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poll_school
     *
     * @mbg.generated Mon Jun 25 16:38:06 CST 2018
     */
    List<School> selectByExample(SchoolExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poll_school
     *
     * @mbg.generated Mon Jun 25 16:38:06 CST 2018
     */
    SchoolWithBLOBs selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poll_school
     *
     * @mbg.generated Mon Jun 25 16:38:06 CST 2018
     */
    int updateByExampleSelective(@Param("record") SchoolWithBLOBs record, @Param("example") SchoolExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poll_school
     *
     * @mbg.generated Mon Jun 25 16:38:06 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") SchoolWithBLOBs record, @Param("example") SchoolExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poll_school
     *
     * @mbg.generated Mon Jun 25 16:38:06 CST 2018
     */
    int updateByExample(@Param("record") School record, @Param("example") SchoolExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poll_school
     *
     * @mbg.generated Mon Jun 25 16:38:06 CST 2018
     */
    int updateByPrimaryKeySelective(SchoolWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poll_school
     *
     * @mbg.generated Mon Jun 25 16:38:06 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(SchoolWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poll_school
     *
     * @mbg.generated Mon Jun 25 16:38:06 CST 2018
     */
    int updateByPrimaryKey(School record);
}